// Code generated by "pass-charm-go-generator"; DO NOT EDIT.

package {{ packagename }}

type CharmConfig struct {
	ConfigOptions		ConfigOptions
	ProxyConfig		ProxyConfig	
	Integrations 		Integrations
}

type ConfigOptions struct {
     Port		string		`env:"APP_PORT"`
     MetricsPort 	*string 	`env:"APP_METRICS_PORT"`
     MetricsPath 	*string 	`env:"APP_METRICS_PATH"`
     LogLevel 	        *string 	`env:"APP_LOG_LEVEL"`
     UserConfigOptions
}

type ProxyConfig struct {
	HTTPProxy 	*string	`env:"HTTP_PROXY"`
	HTTPSProxy 	*string	`env:"HTTPS_PROXY"`
	NoProxy	[]string	`env:"NO_PROXY"`
}

// only put the declared ones in charmcraft.yaml!!!
// if it is optional, with an *, otherwise without it!!
type Integrations struct{
	# MongoURL      *string	`env:"..."`
	# PostgresqlURL *string	`env:"..."`
	# RedisURL      *string	`env:"..."`
	# MysqlURL      *string	`env:"..."`
	# S3            *S3Config
        # SAMLConfig    *SamlConfig
     PostgreSQL *PostgreSQL
}

type PostgreSQL struct{
     
}



type UserConfigOptions struct {
 {{range  .UserOptions}}
     {{ .Name }} {{ .Type }}  `env:"{{ .Variable }}"`
 {{end}}
}